name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push, release]


jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name:
        run: 
          - echo ::set-env name=REV_TYPE::`echo ${GITHUB_REF} | sed -s 's/refs\/\(.*\)\/.*/\1/g'`
          - echo ::set-env name=REF_VERSION::`echo ${GITHUB_REF} | sed -s 's/refs\/\(.*\)\/\(.*/\1/g'`
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'

      - name: Environment
        run:  export
